version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TodoApp-ini-Dev"
s3_bucket = "todobucket.com"
s3_prefix = "TodoApp-ini-Dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
